repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black main.py setup.py checker tests
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest -p no:warning
        types: [python]
