dist: xenial
sudo: false

language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r dev-reqs.txt
  - python setup.py develop

script:
  - pytest  --cov=checker --cov-report=xml -v
after_success:
  codecov
